name: Deploy main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: DEPLOY getManager LAMBDA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: CHECKING OUT CODE
    - uses: actions/checkout@v3
    - name: SETTING UP NODE
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: SERVERLESS DEPLOY
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}